/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@stencil/router';
import '@stencil/state-tunnel';
import '@stencil/redux';


declare global {

  namespace StencilComponents {
    interface AppHome {

    }
  }

  interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-home': JSXElements.AppHomeAttributes;
    }
  }
  namespace JSXElements {
    export interface AppHomeAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface BooksList {
      'items': Array<any>;
    }
  }

  interface HTMLBooksListElement extends StencilComponents.BooksList, HTMLStencilElement {}

  var HTMLBooksListElement: {
    prototype: HTMLBooksListElement;
    new (): HTMLBooksListElement;
  };
  interface HTMLElementTagNameMap {
    'books-list': HTMLBooksListElement;
  }
  interface ElementTagNameMap {
    'books-list': HTMLBooksListElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'books-list': JSXElements.BooksListAttributes;
    }
  }
  namespace JSXElements {
    export interface BooksListAttributes extends HTMLAttributes {
      'items'?: Array<any>;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface SavedBooks {

    }
  }

  interface HTMLSavedBooksElement extends StencilComponents.SavedBooks, HTMLStencilElement {}

  var HTMLSavedBooksElement: {
    prototype: HTMLSavedBooksElement;
    new (): HTMLSavedBooksElement;
  };
  interface HTMLElementTagNameMap {
    'saved-books': HTMLSavedBooksElement;
  }
  interface ElementTagNameMap {
    'saved-books': HTMLSavedBooksElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'saved-books': JSXElements.SavedBooksAttributes;
    }
  }
  namespace JSXElements {
    export interface SavedBooksAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface SearchBox {

    }
  }

  interface HTMLSearchBoxElement extends StencilComponents.SearchBox, HTMLStencilElement {}

  var HTMLSearchBoxElement: {
    prototype: HTMLSearchBoxElement;
    new (): HTMLSearchBoxElement;
  };
  interface HTMLElementTagNameMap {
    'search-box': HTMLSearchBoxElement;
  }
  interface ElementTagNameMap {
    'search-box': HTMLSearchBoxElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'search-box': JSXElements.SearchBoxAttributes;
    }
  }
  namespace JSXElements {
    export interface SearchBoxAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
